# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculateDelta <- function(inputMatrix, inputVector, naExist, resultDelta) {
    invisible(.Call(`_scrat_calculateDelta`, inputMatrix, inputVector, naExist, resultDelta))
}

calculateEuclideanDistances <- function(deltaMatrix, resultEuclideanDistances2) {
    invisible(.Call(`_scrat_calculateEuclideanDistances`, deltaMatrix, resultEuclideanDistances2))
}

calculateNeighborhoodMatrix <- function(winnerNeuronR, somSize, radius, resultVector) {
    invisible(.Call(`_scrat_calculateNeighborhoodMatrix`, winnerNeuronR, somSize, radius, resultVector))
}

matrixToCodebookMatrix <- function(matrixAsVector, result) {
    invisible(.Call(`_scrat_matrixToCodebookMatrix`, matrixAsVector, result))
}

